# Generated by Django 4.0.6 on 2023-02-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='cource_price',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='is_sale',
        ),
    ]
