# Generated by Django 4.0.6 on 2023-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_storeproduct_cource_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='slug',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
