# Generated by Django 4.1.7 on 2023-04-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storeproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_stores/'),
        ),
    ]
