# Generated by Django 4.0.4 on 2023-03-21 15:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_mobile', models.ImageField(blank=True, null=True, upload_to='news_mobile_banner/')),
                ('title_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_mobile', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='news_banner/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
