# Generated by Django 4.1.7 on 2023-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_desc_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
