# Generated by Django 4.0.6 on 2022-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percent',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
