# Generated by Django 4.0.6 on 2022-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_sale_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
