# Generated by Django 4.0.6 on 2023-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
