# Generated by Django 4.0.6 on 2023-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_cource_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='col_md',
            field=models.CharField(choices=[('col-lg-7', 'col-lg-7'), ('col-lg-5', 'col-lg-5'), ('col-lg-4', 'col-lg-4')], default='col-lg-7', max_length=150),
        ),
    ]
