# Generated by Django 4.0.6 on 2023-01-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_col_md'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
