# Generated by Django 4.0.6 on 2023-02-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_likeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproduct',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
