# Generated by Django 4.0.6 on 2023-02-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_likeproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
