# Generated by Django 4.0.6 on 2023-02-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_likeproduct_product_alter_likeproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_category/'),
        ),
    ]
