# Generated by Django 4.0.6 on 2023-02-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0037_category_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
