# Generated by Django 4.0.6 on 2023-02-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
