# Generated by Django 4.0.4 on 2023-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_product_image_remove_product_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Sport eşikleri', 'Sport eşikleri'), ('Aýakgap', 'Aýakgap'), ('Meşhur harytlar', 'Meşhur harytlar'), ('Ýakynlaň üçin', 'Ýakynlaň üçin'), ('Özin üçin', 'Özin üçin')], default='Ayakgap', max_length=150, null=True),
        ),
    ]
