# Generated by Django 4.0.4 on 2023-04-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Egin-eshik', 'Egin-eshik'), ('Oy bezegleri', 'Oy bezegleri'), ('Hojalyk harytlary', 'Hojalyk harytlary'), ('Kompyuter tehnikalary', 'Kompyuter tehnikalary'), ('Gozellik we ideg serishdeleri', 'Gozellik we ideg serishdeleri'), ('Awtobezegler', 'Awtobezegler'), ('Telefon aksessuarlary', 'Telefon aksessuarlary'), ('Sport we guymenje', 'Sport we guymenje'), ('Konselyariya harytlary', 'Konselyariya harytlary'), ('Gap-gachlar', 'Gap-gachlar')], default='Ayakgap', max_length=150, null=True),
        ),
    ]
