# Generated by Django 4.1.7 on 2023-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
    ]
