# Generated by Django 4.0.6 on 2023-01-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile/'),
        ),
    ]
