# Generated by Django 4.0.6 on 2023-02-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salgy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='userprofile/', verbose_name='Müşderi awatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20, verbose_name='Welaýat'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşderi'),
        ),
    ]
