# Generated by Django 4.0.6 on 2022-10-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0002_rename_obyawlinya_categoryad_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obyawleniya.categoryad'),
        ),
    ]
