# Generated by Django 4.0.6 on 2022-11-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0003_alter_ad_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='ad/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='obyawleniya.locations')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obyawleniya.locations'),
        ),
    ]
