# Generated by Django 4.0.4 on 2022-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0004_ad_image_2_ad_image_3_ad_phone_number_ad_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/'),
        ),
    ]
