# Generated by Django 4.0.6 on 2023-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0006_categoryad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='locations',
            field=models.CharField(choices=[('Mary', 'Mary'), ('Ashgabat', 'Ashgabat'), ('Lebap', 'Lebap'), ('Ahal', 'Ahal'), ('Balkan', 'Balkan'), ('Dashoguz', 'Dashoguz')], default='Mary', max_length=150),
        ),
    ]
