# Generated by Django 4.0.6 on 2023-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0007_alter_ad_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='seen_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
