# Generated by Django 4.0.6 on 2023-02-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obyawleniya', '0008_ad_seen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obyawleniya.categoryad', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='credit',
            field=models.BooleanField(default=False, verbose_name='Garaşaryna'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='exchange',
            field=models.BooleanField(default=False, verbose_name='Alyş-çalyş'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='ad_test/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='locations',
            field=models.CharField(choices=[('Mary', 'Mary'), ('Ashgabat', 'Ashgabat'), ('Lebap', 'Lebap'), ('Ahal', 'Ahal'), ('Balkan', 'Balkan'), ('Dashoguz', 'Dashoguz')], default='Mary', max_length=150, verbose_name='Ýerleşýän ýeri'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon belgi'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Bahasy $'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='seen_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Görülenler'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşderi'),
        ),
        migrations.AlterField(
            model_name='categoryad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_ads/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='categoryad',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='obyawleniya.locations', verbose_name='Esasy'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Beýany'),
        ),
    ]
