# Generated by Django 4.0.4 on 2023-04-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0009_alter_ad_cat_id_alter_ad_credit_alter_ad_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
    ]
