# Generated by Django 4.0.4 on 2023-05-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0010_remove_ad_credit_remove_ad_exchange_remove_ad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='locations',
        ),
    ]
