# Generated by Django 4.0.4 on 2023-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obyawleniya', '0011_remove_ad_cat_id_remove_ad_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='locations',
            field=models.CharField(default=1, max_length=255, verbose_name='Ýerleşýän ýeri'),
            preserve_default=False,
        ),
    ]
