# Generated by Django 4.0.6 on 2022-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_variation_product_variation_product'),
        ('orders', '0003_remove_orderproduct_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
