# Generated by Django 4.0.6 on 2022-10-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_ordered_alter_order_is_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
    ]
