# Generated by Django 4.0.4 on 2022-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_1', models.ImageField(blank=True, null=True, upload_to='slider_banner/')),
                ('slider_image_2', models.ImageField(blank=True, null=True, upload_to='slider_banner/')),
                ('slider_image_3', models.ImageField(blank=True, null=True, upload_to='slider_banner/')),
                ('lilte_banner_1', models.ImageField(blank=True, null=True, upload_to='litle_banner/')),
                ('lilte_banner_2', models.ImageField(blank=True, null=True, upload_to='litle_banner/')),
                ('big_banner_2', models.ImageField(blank=True, null=True, upload_to='big_banner/')),
            ],
        ),
    ]
