# Generated by Django 4.0.6 on 2022-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='big_banner_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='lilte_banner_1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='lilte_banner_2',
        ),
        migrations.AddField(
            model_name='slider',
            name='hot_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_mini_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
