# Generated by Django 4.0.6 on 2022-10-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_remove_slider_big_banner_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='hot_detail',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_mini_title',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_title',
        ),
    ]
