# Generated by Django 4.0.6 on 2022-10-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_slider_hot_detail_slider_slider_mini_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_image_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slider_image_3',
        ),
    ]
