# Generated by Django 4.0.6 on 2022-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_remove_slider_slider_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lilte_banner_1', models.ImageField(blank=True, null=True, upload_to='litle_banner/')),
                ('lilte_banner_2', models.ImageField(blank=True, null=True, upload_to='litle_banner/')),
                ('slider_title', models.CharField(blank=True, max_length=100, null=True)),
                ('slider_mini_title', models.CharField(blank=True, max_length=100, null=True)),
                ('big_banner_2', models.ImageField(blank=True, null=True, upload_to='big_banner/')),
            ],
        ),
    ]
