# Generated by Django 4.0.6 on 2022-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_topproduct_topminiproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
