# Generated by Django 4.0.6 on 2022-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='store_banner/'),
        ),
    ]
