# Generated by Django 4.0.4 on 2022-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0013_logo_image_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='checkout_banner/')),
            ],
        ),
    ]
