# Generated by Django 4.0.6 on 2023-01-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_checkoutbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_image_1',
            new_name='slider_image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='hot_detail',
        ),
    ]
