# Generated by Django 4.0.6 on 2023-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_rename_slider_image_1_slider_slider_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproduct',
            name='mini_desc_4',
        ),
        migrations.AddField(
            model_name='topproduct',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
