# Generated by Django 4.0.6 on 2023-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_remove_topproduct_mini_desc_4_topproduct_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerForCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Charity/')),
            ],
        ),
        migrations.DeleteModel(
            name='VipAd',
        ),
    ]
