# Generated by Django 4.0.6 on 2023-02-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0017_bannerforcharity_delete_vipad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerforcharity',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_charity_banner/'),
        ),
        migrations.AddField(
            model_name='minislider',
            name='slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_slider_banner/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_slider_banner/'),
        ),
    ]
