# Generated by Django 4.0.6 on 2023-02-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_category_mobile_image'),
        ('banner', '0018_bannerforcharity_image_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerforcharity',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='bannerforcharity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Charity/', verbose_name='Suraty'),
        ),
        migrations.AlterField(
            model_name='bannerforcharity',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_charity_banner/', verbose_name='Mobile suraty'),
        ),
        migrations.AlterField(
            model_name='bannerforcharity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='cartbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banner/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='checkoutbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checkout_banner/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banner/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='store_banner/', verbose_name='Mobile logo'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='big_banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='big_banner/', verbose_name='Uly banner'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='lilte_banner_1',
            field=models.ImageField(blank=True, null=True, upload_to='litle_banner/', verbose_name='Kiçi banner'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='lilte_banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='litle_banner/', verbose_name='Kiçi banner 2'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='slider_mini_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiçi banneriň gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_slider_banner/', verbose_name='Mobile banner'),
        ),
        migrations.AlterField(
            model_name='minislider',
            name='slider_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kiçi banneryň beýany'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_banner/', verbose_name='Slider suraty'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_mini_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider gysgaça beýan'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_slider_banner/', verbose_name='Mobile surat'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web slider'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banner/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Beýan'),
        ),
        migrations.AlterField(
            model_name='topminiproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Haryt'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salgysy'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýan'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýan'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='mini_desc_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Beýan'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Haryt'),
        ),
    ]
