# Generated by Django 4.0.4 on 2023-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0021_miniaboutusleft_miniaboutusright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniaboutusleft',
            name='mini_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gysgacha beyany'),
        ),
    ]
