# Generated by Django 4.0.4 on 2023-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0022_alter_miniaboutusleft_mini_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='slider_banner/', verbose_name='gif suraty')),
            ],
        ),
    ]
